/**
 * research/src/interpretation/ExplainabilityEngine.js
 *
 * Purpose:
 *   Generates the full structured explanation object for a Phase 11
 *   candidate — directive's "Explainability Engine" spec: plain-English
 *   summary, 3-form machine-readable mathematics, context description,
 *   cautious interpretation (honest about the PRNG nature of Deriv
 *   synthetic indices), known limitations, uncertainty estimates,
 *   scientific/trading importance, stability index, evidence tier,
 *   implementation maturity, a clearly-labeled non-scientific "Operational
 *   Trading Note," a disclaimer, and a reference into the
 *   DecisionAuditLog.
 *
 * Scientific rationale for the disclaimer discipline: Deriv's synthetic
 *   indices are PRNG-generated (documented project-wide, e.g.
 *   proxy/coreProxies.js's honest-naming convention and this user's own
 *   established position that indicators serve as trend filters improving
 *   confluence rather than direct predictors of an RNG-driven series).
 *   Every explanation this engine produces must say so explicitly and must
 *   not imply the candidate has "found the pattern" in a market-structure
 *   sense that would not apply to synthetic instruments.
 *
 * Composition, not reimplementation: this module is a thin assembler over
 *   already-built Phase 11 pieces — plugin/MachineReadableMathematics.js
 *   for the 3-form math, governance/scientificEvidenceTiers.js /
 *   implementationMaturity.js for the tier/maturity labels, and whatever
 *   uncertainty/stability/importance values the caller has already
 *   computed (analysis/DiscoveryStabilityAnalysis.js,
 *   analysis/ImportanceScorer.js) — it does not compute any statistic
 *   itself.
 *
 * Dependencies: plugin/MachineReadableMathematics.js (validation only).
 * Public API: explainCandidate, InvalidExplanationInputError.
 * Complexity: O(1).
 */

import { validateMathDefinition } from '../plugin/MachineReadableMathematics.js';

export class InvalidExplanationInputError extends Error {
  constructor(message) {
    super(message);
    this.name = 'InvalidExplanationInputError';
  }
}

const PRNG_DISCLAIMER =
  'Deriv synthetic indices are generated by a pseudo-random number generator (PRNG), not by real-world ' +
  'supply/demand order flow. This explanation describes a statistically estimated pattern in that PRNG-driven ' +
  'series — it is not evidence of market-structure behavior (e.g. genuine institutional order flow), and the ' +
  'proxy/indicator names used are estimates, not proof of any such behavior.';

/**
 * Builds the full explanation object for a candidate. Every numeric/scored
 * input is caller-supplied (already computed elsewhere in the pipeline) —
 * this function only assembles and formats them, and enforces the
 * presence of the required disclaimer and plain-English length cap.
 *
 * @param {object} params
 * @param {import('../candidate/Candidate.js').Candidate} params.candidate
 * @param {string} params.plainEnglishSummary - MUST be ≤ 3 sentences (checked
 *   by counting sentence-terminal punctuation; not a substitute for human
 *   review, but catches the common failure mode of a pasted-in long summary).
 * @param {object} params.mathDefinition - A MathDefinition object as created
 *   by plugin/MachineReadableMathematics.js's createMathDefinition
 *   (humanReadable, symbolicExpression, executableFormula, units, domain, range).
 * @param {string} params.contextDescription - Description of the observable
 *   context(s) this candidate/hypothesis is conditioned on.
 * @param {string} params.interpretation - Cautious, PRNG-aware interpretation.
 * @param {string[]} params.knownLimitations
 * @param {{estimate: number, se: number, ci95: [number, number], sampleSize: number, replicationCount: number}} params.uncertainty
 *   Constraint #7: every reported quantity requires estimate, SE, 95% CI, n, replication count.
 * @param {number|null} [params.scientificImportance=null] - From ImportanceScorer (post-confirmation only).
 * @param {number|null} [params.tradingImportance=null] - From ImportanceScorer (post-confirmation only).
 * @param {number|null} [params.discoveryStabilityIndex=null] - From DiscoveryStabilityAnalysis.
 * @param {string} [params.operationalTradingNote] - Clearly labeled, non-scientific, demo-only note.
 * @param {object[]} [params.decisionAuditTrailRef=[]] - Reference entries (e.g. from DecisionAuditLog.forCandidate()).
 * @returns {object} The full explanation record.
 */
export function explainCandidate({
  candidate,
  plainEnglishSummary,
  mathDefinition,
  contextDescription,
  interpretation,
  knownLimitations,
  uncertainty,
  scientificImportance = null,
  tradingImportance = null,
  discoveryStabilityIndex = null,
  operationalTradingNote = null,
  decisionAuditTrailRef = [],
} = {}) {
  const errors = [];

  if (!candidate || !candidate.id) errors.push('candidate: a candidate with an id is required');

  if (!plainEnglishSummary || typeof plainEnglishSummary !== 'string') {
    errors.push('plainEnglishSummary: required non-empty string');
  } else {
    const sentenceCount = (plainEnglishSummary.match(/[.!?]+(\s|$)/g) || []).length || 1;
    if (sentenceCount > 3) {
      errors.push(`plainEnglishSummary: must be at most 3 sentences (counted ${sentenceCount})`);
    }
  }

  const mathCheck = validateMathDefinition(mathDefinition);
  if (!mathCheck.valid) errors.push(...mathCheck.errors.map(e => `mathDefinition: ${e}`));

  if (!contextDescription || typeof contextDescription !== 'string') {
    errors.push('contextDescription: required non-empty string');
  }
  if (!interpretation || typeof interpretation !== 'string') {
    errors.push('interpretation: required non-empty string');
  }
  if (!Array.isArray(knownLimitations) || knownLimitations.length === 0) {
    errors.push('knownLimitations: required non-empty array of strings');
  }

  if (!uncertainty || typeof uncertainty !== 'object') {
    errors.push('uncertainty: required object');
  } else {
    for (const field of ['estimate', 'se', 'sampleSize', 'replicationCount']) {
      if (typeof uncertainty[field] !== 'number' || !Number.isFinite(uncertainty[field])) {
        errors.push(`uncertainty.${field}: required finite number`);
      }
    }
    if (!Array.isArray(uncertainty.ci95) || uncertainty.ci95.length !== 2 ||
        uncertainty.ci95.some(v => typeof v !== 'number' || !Number.isFinite(v))) {
      errors.push('uncertainty.ci95: required 2-element array of finite numbers [lower, upper]');
    }
  }

  if (errors.length) throw new InvalidExplanationInputError(errors.join('; '));

  return Object.freeze({
    candidateId: candidate.id,
    fingerprint: candidate.fingerprint,
    plainEnglish: plainEnglishSummary,
    mathematics: { ...mathDefinition },
    contextDescription,
    interpretation,
    knownLimitations: [...knownLimitations],
    uncertainty: {
      estimate: uncertainty.estimate,
      se: uncertainty.se,
      ci95: [...uncertainty.ci95],
      sampleSize: uncertainty.sampleSize,
      replicationCount: uncertainty.replicationCount,
    },
    scientificImportance,
    tradingImportance,
    discoveryStabilityIndex,
    evidenceTier: candidate.evidenceTier,
    implementationMaturity: candidate.implementationMaturity,
    operationalTradingNote: operationalTradingNote
      ? `[OPERATIONAL / NON-SCIENTIFIC / DEMO ONLY] ${operationalTradingNote}`
      : null,
    disclaimer: PRNG_DISCLAIMER,
    decisionAuditTrailRef: [...decisionAuditTrailRef],
    generatedAt: Date.now(),
  });
}
