/**
 * ai/narrativeEngine.js
 *
 * Smart Market Intelligence: turns the MTF module's existing analysis
 * engines into an institutional-style natural-language report — no raw
 * indicators, gauges, or percentages shown to the user, only conclusions.
 * Internally, every sentence traces back to a specific, inspectable
 * condition from Phases 11-14 plus the new historical-similarity module;
 * nothing here is generated by an external AI model.
 *
 * SCOPE, STATED DIRECTLY: the "synchronized multi-timeframe narrative"
 * covers exactly the two timeframes this app actually has data for — the
 * HTF and LTF panels, at whatever granularity is currently selected (e.g.
 * "1H" and "1min", not fabricated "Daily/M15/M5" labels). A genuine
 * 6-rung Daily→H4→H1→M15→M5→M1 cascade would require fetching four more
 * independent timeframes — real new data infrastructure, not just a
 * narrative layer on top of what's already loaded. That's out of scope
 * here; this synthesizes what the app actually has, honestly labeled.
 *
 * @typedef {Object} IntelligenceReport
 * @property {'bullish'|'bearish'|'ranging'|'neutral'} bias
 * @property {string} narrative
 * @property {Array<{label:string, text:string}>} mtfNarrative
 * @property {{verdict:'Rise'|'Fall'|'Wait', reasoning:string[]}} tradeAssessment
 * @property {string[]} evidence
 * @property {string[]} risks
 * @property {string} historicalContext
 * @property {boolean} sufficientData
 */

import { computeStats } from '../analysis/statistics.js';
import { computeOrderFlow } from '../orderflow/proxy.js';
import { runPatternScan } from '../analysis/patternEngine.js';
import { runRuleEngine } from './ruleEngine.js';
import { inferOverallTrend } from '../analysis/structurePatterns.js';
import { findHistoricalAnalogs } from '../analysis/historicalSimilarity.js';
import { decimalsFor } from '../utils/geometry.js';

const MIN_CANDLES = 40;

function pct(n) { return `${Math.round(n)}%`; }

/**
 * @param {Array} htfCandles
 * @param {Array} ltfCandles
 * @param {{htfLabel:string, ltfLabel:string}} tfLabels
 * @returns {IntelligenceReport}
 */
export function generateIntelligenceReport(htfCandles, ltfCandles, tfLabels) {
  if (!htfCandles || htfCandles.length < MIN_CANDLES) {
    return {
      bias: 'neutral', sufficientData: false,
      narrative: 'Not enough candle history has loaded yet on the higher timeframe to produce a reliable report. This updates automatically as more data arrives.',
      mtfNarrative: [], tradeAssessment: { verdict: 'Wait', reasoning: ['Insufficient data loaded to assess the market with confidence.'] },
      evidence: [], contradictingEvidence: [], risks: [], historicalContext: '',
    };
  }

  const stats = computeStats(htfCandles);
  const flow = computeOrderFlow(htfCandles);
  const findings = runPatternScan(htfCandles);
  const ruleResults = runRuleEngine(htfCandles);
  const trend = inferOverallTrend(htfCandles);
  const analogs = findHistoricalAnalogs(htfCandles);

  const bias = deriveBias(trend, ruleResults, flow);
  const narrative = buildNarrative(htfCandles, findings, ruleResults, flow, stats, bias);
  const mtfNarrative = buildMtfNarrative(htfCandles, ltfCandles, tfLabels, trend, findings, flow);
  const tradeAssessment = buildTradeAssessment(bias, ruleResults, flow, findings);
  const evidence = buildEvidence(bias, flow, stats, findings, ruleResults);
  const contradictingEvidence = buildContradictingEvidence(bias, flow, stats, findings, analogs, htfCandles.length);
  const risks = buildRisks(bias);
  const historicalContext = buildHistoricalContext(analogs);

  return { bias, sufficientData: true, narrative, mtfNarrative, tradeAssessment, evidence, contradictingEvidence, risks, historicalContext };
}

function deriveBias(trend, ruleResults, flow) {
  const cont = ruleResults.find(r => r.type === 'bullishContinuation' || r.type === 'bearishContinuation');
  if (cont) return cont.type === 'bullishContinuation' ? 'bullish' : 'bearish';
  const reversal = ruleResults.find(r => r.type === 'reversal');
  if (reversal && reversal.confidence >= 65) return reversal.direction === 'bullish' ? 'bullish' : 'bearish';
  if (ruleResults.some(r => r.type === 'accumulation' || r.type === 'distribution')) return 'ranging';
  if (trend === 'up' && flow.buyingPressurePct > 52) return 'bullish';
  if (trend === 'down' && flow.sellingPressurePct > 52) return 'bearish';
  return 'neutral';
}

function buildNarrative(candles, findings, ruleResults, flow, stats, bias) {
  const sentences = [];
  const dirWord = bias === 'bullish' ? 'buyers' : bias === 'bearish' ? 'sellers' : 'neither side';
  const recent = f => f.index >= candles.length - 10;

  const sweep = findings.find(f => f.type === 'liquiditySweep' && recent(f));
  const choch = findings.find(f => f.type === 'choch' && recent(f));
  const bos = findings.find(f => f.type === 'bos' && recent(f));

  if (sweep) {
    sentences.push(`Price recently swept ${sweep.direction === 'bearish' ? 'buy-side' : 'sell-side'} liquidity at ${sweep.sweptLevel.toFixed(decimalsFor(sweep.sweptLevel))} before reversing back inside the prior range.`);
  }
  if (choch) {
    sentences.push(`This was followed by a ${choch.direction} change of character, the first sign the prevailing trend may be shifting.`);
  }
  if (bos) {
    sentences.push(`A ${bos.direction} break of structure then confirmed ${bos.direction === 'bullish' ? 'buyers' : 'sellers'} had regained control, closing beyond the prior swing ${bos.direction === 'bullish' ? 'high' : 'low'} at ${bos.brokenLevel.toFixed(decimalsFor(bos.brokenLevel))}.`);
  }

  const contFinding = ruleResults.find(r => r.type === 'bullishContinuation' || r.type === 'bearishContinuation');
  if (contFinding) {
    sentences.push(`Momentum has since expanded in the direction of the move, with pullbacks remaining shallow — a sign of sustained ${contFinding.direction === 'bullish' ? 'buying' : 'selling'} pressure rather than exhaustion.`);
  } else if (Math.abs(stats.momentumPct) < 1.5 && flow.absorption < 0.35) {
    sentences.push(`Price has moved sideways with real range being traded but little net progress — consistent with ${bias === 'ranging' ? 'accumulation or distribution rather than a directed trend' : 'indecision'}.`);
  }

  if (!sentences.length) {
    sentences.push(`No decisive structural event has occurred recently on this timeframe; ${dirWord} currently hold a slight edge based on candle balance and order-flow pressure alone.`);
  }

  const trendStrength = ruleResults.find(r => r.type === 'trendStrength');
  if (trendStrength && trendStrength.direction) {
    sentences.push(`The higher-timeframe trend remains ${trendStrength.direction === 'up' ? 'upward' : 'downward'}${trendStrength.confidence >= 60 ? ' and well-established' : ', though not yet strongly confirmed'}.`);
  }

  // Consistency guard: if the text above described a directional event
  // (sweep/CHoCH/BOS) but the overall bias still came out neutral/ranging —
  // meaning order-flow didn't confirm it strongly enough to fully commit —
  // say so explicitly, rather than leaving confident-sounding event language
  // sitting next to a conclusion that doesn't match its tone.
  const describedDirectionalEvent = Boolean(sweep || choch || bos);
  if (describedDirectionalEvent && (bias === 'neutral' || bias === 'ranging')) {
    sentences.push('However, order-flow confirmation for this move remains inconclusive, which tempers confidence in treating this as a fully established directional bias for now.');
  }

  return sentences.join(' ');
}

function buildMtfNarrative(htfCandles, ltfCandles, tfLabels, htfTrend, findings, flow) {
  const rungs = [];

  const htfChoch = [...findings].reverse().find(f => f.type === 'choch');
  let htfText;
  if (htfTrend) {
    htfText = `${htfTrend === 'up' ? 'Bullish' : 'Bearish'} trend ${htfChoch ? 'is being challenged by a recent change of character' : 'remains intact'}.`;
  } else {
    htfText = 'No clear directional trend is established on this timeframe.';
  }
  rungs.push({ label: tfLabels.htfLabel, text: htfText });

  if (ltfCandles && ltfCandles.length >= 20) {
    const ltfStats = computeStats(ltfCandles);
    const ltfFlow = computeOrderFlow(ltfCandles);
    let ltfText;
    if (ltfStats && ltfFlow) {
      const ltfDir = ltfFlow.buyingPressurePct > ltfFlow.sellingPressurePct ? 'buyers' : 'sellers';
      const aligned = (htfTrend === 'up' && ltfDir === 'buyers') || (htfTrend === 'down' && ltfDir === 'sellers');
      ltfText = `${ltfDir === 'buyers' ? 'Buying' : 'Selling'} pressure dominates (${pct(Math.max(ltfFlow.buyingPressurePct, ltfFlow.sellingPressurePct))})${aligned ? ', supporting the higher-timeframe move' : ', currently diverging from the higher-timeframe trend'}.`;
    } else {
      ltfText = 'Not enough lower-timeframe data loaded yet to assess.';
    }
    rungs.push({ label: tfLabels.ltfLabel, text: ltfText });
  }

  return rungs;
}

function buildTradeAssessment(bias, ruleResults, flow, findings) {
  const reasoning = [];
  let verdict = 'Wait';

  const cont = ruleResults.find(r => r.type === 'bullishContinuation' || r.type === 'bearishContinuation');
  const reversal = ruleResults.find(r => r.type === 'reversal');

  if (bias === 'bullish' && cont && cont.confidence >= 60) {
    verdict = 'Rise';
    reasoning.push('Current evidence suggests buyers remain in control.');
    reasoning.push(flow.buyingPressurePct > 60 ? 'No significant signs of exhaustion are detected.' : 'Buying pressure is positive but not yet overwhelming — position sizing should reflect that.');
    reasoning.push('The probability currently favors continuation rather than reversal.');
  } else if (bias === 'bearish' && cont && cont.confidence >= 60) {
    verdict = 'Fall';
    reasoning.push('Current evidence suggests sellers remain in control.');
    reasoning.push(flow.sellingPressurePct > 60 ? 'No significant signs of exhaustion are detected.' : 'Selling pressure is negative but not yet overwhelming — position sizing should reflect that.');
    reasoning.push('The probability currently favors continuation rather than reversal.');
  } else if (reversal && reversal.confidence >= 65) {
    verdict = 'Wait';
    reasoning.push(`A ${reversal.direction} change of character was recently detected — the prevailing trend may be turning.`);
    reasoning.push('Entering in the prior trend direction carries elevated risk until the new structure confirms.');
  } else {
    verdict = 'Wait';
    reasoning.push('Evidence is currently mixed — no clearly dominant side has emerged.');
    reasoning.push('Waiting for a decisive structure break or a clear order-flow imbalance is the more conservative approach here.');
  }

  return { verdict, reasoning };
}

function buildEvidence(bias, flow, stats, findings, ruleResults) {
  const ev = [];
  if (bias === 'bullish') {
    if (flow.buyingPressurePct > 55) ev.push('Buyers are defending higher prices.');
    if (stats.avgWickSize < stats.avgBodySize) ev.push('Pullbacks remain shallow relative to the size of the moves.');
    if (!findings.some(f => f.type === 'choch' && f.direction === 'bearish' && f.index >= findings.length - 10)) ev.push('No significant bearish market structure break has been detected recently.');
  } else if (bias === 'bearish') {
    if (flow.sellingPressurePct > 55) ev.push('Sellers are defending lower prices.');
    if (stats.avgWickSize < stats.avgBodySize) ev.push('Pullbacks remain shallow relative to the size of the moves.');
    if (!findings.some(f => f.type === 'choch' && f.direction === 'bullish' && f.index >= findings.length - 10)) ev.push('No significant bullish market structure break has been detected recently.');
  }
  if (Math.abs(stats.momentumPct) > 1) ev.push(`Momentum is ${stats.momentumPct > 0 ? 'increasing to the upside' : 'increasing to the downside'} (${stats.momentumPct >= 0 ? '+' : ''}${stats.momentumPct.toFixed(2)}% net over the visible range).`);
  if (bias === 'bullish' || bias === 'bearish') {
    ev.push(`Order-flow proxy favors ${flow.buyingPressurePct > flow.sellingPressurePct ? 'buyers' : 'sellers'} (${pct(Math.max(flow.buyingPressurePct, flow.sellingPressurePct))} of directional pressure).`);
  }
  const trendStrength = ruleResults.find(r => r.type === 'trendStrength');
  if (trendStrength && trendStrength.confidence >= 60) ev.push('Structure breaks have consistently favored the current trend direction.');
  if (!ev.length) ev.push('No single factor currently dominates — evidence is balanced between both sides.');
  return ev;
}

/**
 * What works AGAINST the current bias — distinct from risks/invalidation
 * (which are forward-looking "what would break this"), this is present-
 * tense: evidence that already exists right now but doesn't fit the
 * dominant narrative. An institutional report that only lists supporting
 * evidence isn't a fair read of the market; this is the counterweight.
 */
function buildContradictingEvidence(bias, flow, stats, findings, analogs, candleCount) {
  const ev = [];
  const recent = f => f.index >= candleCount - 10;

  if (bias === 'bullish') {
    if (flow.sellingPressurePct > 35) ev.push(`Selling pressure is not negligible (${pct(flow.sellingPressurePct)} of directional pressure) — the move is not entirely one-sided.`);
    if (findings.some(f => f.type === 'pinBar' && f.direction === 'bearish' && recent(f))) ev.push('A bearish pin bar has formed recently, signaling some rejection from higher prices.');
    if (findings.some(f => f.type === 'engulfing' && f.direction === 'bearish' && recent(f))) ev.push('A bearish engulfing candle appeared recently within the current move.');
    if (stats.volatilityPct > 60) ev.push('Volatility is elevated, meaning recent gains could unwind quickly if sentiment shifts.');
  } else if (bias === 'bearish') {
    if (flow.buyingPressurePct > 35) ev.push(`Buying pressure is not negligible (${pct(flow.buyingPressurePct)} of directional pressure) — the move is not entirely one-sided.`);
    if (findings.some(f => f.type === 'pinBar' && f.direction === 'bullish' && recent(f))) ev.push('A bullish pin bar has formed recently, signaling some rejection from lower prices.');
    if (findings.some(f => f.type === 'engulfing' && f.direction === 'bullish' && recent(f))) ev.push('A bullish engulfing candle appeared recently within the current move.');
    if (stats.volatilityPct > 60) ev.push('Volatility is elevated, meaning recent losses could reverse quickly if sentiment shifts.');
  } else {
    ev.push('With no clearly dominant bias established, the case for a strong directional continuation in either direction is currently limited.');
  }

  if (analogs && analogs.sampleSize >= 3 && analogs.reversedPct > 30) {
    ev.push(`Historically, comparable setups still reversed ${pct(analogs.reversedPct)} of the time in the loaded data — a meaningful minority outcome, not a certainty.`);
  }

  if (!ev.length) ev.push('No significant contradicting evidence currently stands out.');
  return ev;
}

function buildRisks(bias) {
  if (bias === 'bullish') {
    return [
      'A bearish change of character forms on the higher timeframe.',
      'Momentum begins contracting rather than expanding.',
      'Buyers fail to defend the most recent higher low.',
    ];
  }
  if (bias === 'bearish') {
    return [
      'A bullish change of character forms on the higher timeframe.',
      'Momentum begins contracting rather than expanding.',
      'Sellers fail to defend the most recent lower high.',
    ];
  }
  if (bias === 'ranging') {
    return [
      'A decisive break of the current range, on strong momentum, would end the ranging condition.',
      'A sudden order-flow imbalance in either direction would signal accumulation/distribution is resolving.',
    ];
  }
  return ['No clear bias currently exists — any decisive structure break in either direction would establish one.'];
}

function buildHistoricalContext(analogs) {
  if (!analogs || analogs.currentTrend === null) {
    return 'Not enough historical structure is available in the loaded data to draw a meaningful comparison to past setups.';
  }
  if (analogs.sampleSize < 3) {
    return `Only ${analogs.sampleSize} comparable historical structure${analogs.sampleSize === 1 ? '' : 's'} were found in the currently loaded history — too few to draw a confident conclusion. This will become more reliable as more history loads.`;
  }
  const dirWord = analogs.currentTrend === 'up' ? 'bullish' : 'bearish';
  const dominant = analogs.continuedPct >= analogs.reversedPct ? 'continued' : 'reversed';
  return `The current structure closely resembles ${analogs.sampleSize} previous ${dirWord} setups in the loaded history. ` +
    `Of those, ${pct(analogs.continuedPct)} continued in the same direction and ${pct(analogs.reversedPct)} reversed — ` +
    `historically, similar structures have more often ${dominant} than done the opposite in this data.`;
}
