/**
 * ui/fiveMinCommentaryPanel.js
 *
 * Renders the 5-Minute AI Market Commentary on the Njanja Analysis page.
 * Reads AppState.timeframePanels['m5'] specifically — this report is
 * intentionally hardcoded to the 5-minute timeframe, not tied to whatever
 * is currently the "active analysis" timeframe elsewhere on the page.
 * Auto-updates on the same panel:dataUpdated event every other live
 * section already uses, so it recomputes the instant new 5-minute candle
 * data arrives — no manual refresh.
 */

import { AppState } from '../core/AppState.js';
import { eventBus } from '../core/EventBus.js';
import { $ } from '../utils/dom.js';
import { generateFiveMinCommentary } from '../ai/fiveMinCommentary.js';
import { decimalsFor } from '../utils/geometry.js';

const TREND_COLOR = {
  'Bullish Continuation': '#1fdf9b', 'Bullish Reversal': '#1fdf9b',
  'Bearish Continuation': '#ff4d6a', 'Bearish Reversal': '#ff4d6a',
  'Consolidation': '#94a3b8',
};

function render() {
  const wrap = $('mtfFiveMinCommentary');
  if (!wrap) return;
  const panel = AppState.timeframePanels['m5'];
  if (!panel) { wrap.innerHTML = `<div class="manager-empty">5-minute panel not yet available.</div>`; return; }

  const report = generateFiveMinCommentary(panel.candles);
  if (!report) {
    wrap.innerHTML = `<div class="manager-empty">Waiting for enough 5-minute history to load before generating commentary.</div>`;
    return;
  }

  const color = TREND_COLOR[report.trendLabel] || '#94a3b8';
  const dec = decimalsFor(panel.candles[panel.candles.length - 1]?.close ?? 1);

  wrap.innerHTML = `
    <div class="smi-section">
      <div class="smi-title">Current Trend</div>
      <div class="smi-verdict" style="color:${color}">${report.trendLabel}</div>
      <p class="smi-prose">${report.trendNarrative}</p>
    </div>

    <div class="smi-section">
      <div class="smi-title">Candle Psychology</div>
      <p class="smi-prose">${report.candlePsychology.intro}</p>
      <ul class="smi-list">${report.candlePsychology.bullets.map(b => `<li>${b}</li>`).join('')}</ul>
      <p class="smi-prose">${report.candlePsychology.closing}</p>
    </div>

    <div class="smi-section">
      <div class="smi-title">Momentum Analysis</div>
      <p class="smi-prose">Momentum remains ${report.momentum.direction}.</p>
      <div class="smi-prose" style="margin-bottom:4px; font-weight:700; font-size:10px; text-transform:uppercase; letter-spacing:.06em; color:var(--mtf-muted)">Observations</div>
      <ul class="smi-list">${report.momentum.observations.map(o => `<li>${o}</li>`).join('')}</ul>
    </div>

    <div class="smi-section">
      <div class="smi-title">Institutional Order Flow</div>
      <p class="smi-prose">Institutional activity suggests ${report.orderFlow.buyersInControl ? 'buyers' : 'sellers'} remain in control.</p>
      <div class="smi-prose" style="margin-bottom:4px; font-weight:700; font-size:10px; text-transform:uppercase; letter-spacing:.06em; color:var(--mtf-muted)">Current Observations</div>
      <ul class="smi-list">${report.orderFlow.observations.map(o => `<li>${o}</li>`).join('')}</ul>
    </div>

    <div class="smi-section">
      <div class="smi-title">Support and Resistance</div>
      <div class="smi-prose" style="margin-bottom:4px; font-weight:700; font-size:10px; text-transform:uppercase; letter-spacing:.06em; color:var(--mtf-muted)">Nearest Support</div>
      ${report.supportResistance.support ? `
        <ul class="smi-list">
          <li>${report.supportResistance.support.label} (${report.supportResistance.support.price.toFixed(dec)})</li>
          <li>${report.supportResistance.support.description}</li>
        </ul>` : `<p class="smi-prose" style="color:var(--mtf-muted)">No swing low currently sits below price in the loaded history.</p>`}
      <div class="smi-prose" style="margin:8px 0 4px; font-weight:700; font-size:10px; text-transform:uppercase; letter-spacing:.06em; color:var(--mtf-muted)">Nearest Resistance</div>
      ${report.supportResistance.resistance ? `
        <ul class="smi-list">
          <li>${report.supportResistance.resistance.label} (${report.supportResistance.resistance.price.toFixed(dec)})</li>
          <li>${report.supportResistance.resistance.description}</li>
        </ul>` : `<p class="smi-prose" style="color:var(--mtf-muted)">No swing high currently sits above price in the loaded history.</p>`}
      <div class="smi-prose" style="margin:8px 0 4px; font-weight:700; font-size:10px; text-transform:uppercase; letter-spacing:.06em; color:var(--mtf-muted)">Potential Warning Signs</div>
      <ul class="smi-list smi-list-risk">${report.warningSigns.map(w => `<li>${w}</li>`).join('')}</ul>
    </div>

    <div class="smi-disclaimer">Deterministic, rule-based commentary generated from this module's own analysis engines — not a prediction, not financial advice, and not generated by an external AI model.</div>
  `;
}

export function initFiveMinCommentaryPanel() {
  eventBus.on('panel:dataUpdated', ({ panel }) => { if (panel.side === 'm5') render(); });
  render();
}
